#!/usr/bin/env python3
"""nosf_analyze.py — offline regression on nosf_logger.py CSVs.

Reads one or more CSVs, buckets rows by (feature, v_fil_bin), fits
per-bucket statistics, and emits a config.ini patch with suggested
BASELINE_SPS, SYNC_TRAILING_BIAS_FRAC, and optionally per-feature
feedforward coefficients.

Usage: nosf_analyze.py --in run1.csv run2.csv --out config.patch.ini
       [--mode safe|aggressive] [--feedforward]
"""
import argparse, configparser, csv, math, sys
from collections import defaultdict
import statistics as stats

SAFETY_K = {'safe': 1.5, 'aggressive': 1.0}     # σ-multiplier on baseline reserve

def bin_v_fil(v): return int(round(float(v) / 5.0)) * 5  # 5 mm/s buckets

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--in', dest='inputs', nargs='+', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--mode', choices=['safe','aggressive'], default='safe')
    ap.add_argument('--feedforward', action='store_true')
    args = ap.parse_args()

    rows = []
    for path in args.inputs:
        try:
            with open(path) as fh:
                rows.extend(list(csv.DictReader(fh)))
        except FileNotFoundError:
            print(f"Error: file {path} not found")
            continue

    if not rows:
        print("Error: No data rows found")
        sys.exit(1)

    # 1. Bucket by (feature, v_fil_bin)
    buckets = defaultdict(list)
    for r in rows:
        try:
            v = float(r.get('v_fil') or 0.0)
            est = float(r.get('est_sps') or 0.0)
            zone = r.get('zone','')
            if v > 0 and est > 0 and zone == 'MID':
                buckets[(r.get('feature',''), bin_v_fil(v))].append(est)
        except ValueError:
            continue

    # 2. Per-bucket statistics
    summary = {}
    for key, vs in buckets.items():
        if len(vs) < 30: continue              # sparse bucket → skip
        summary[key] = {
            'n': len(vs),
            'mean': stats.mean(vs),
            'stdev': stats.stdev(vs) if len(vs) > 1 else 0.0,
        }

    # 3. Global recommendation: baseline = max bucket mean − k·stdev
    means = [s['mean'] for s in summary.values()]
    if not means:
        print('not enough data; need at least one populated bucket', file=sys.stderr)
        # Fallback to just est_sps mean if no buckets
        all_est = [float(r.get('est_sps') or 0.0) for r in rows if r.get('zone','')=='MID' and float(r.get('est_sps') or 0.0) > 0]
        if not all_est:
            sys.exit(1)
        means = [stats.mean(all_est)]
        stdev = stats.stdev(all_est) if len(all_est) > 1 else 0.0
    else:
        stdev = stats.stdev(means) if len(means) > 1 else 0.0

    suggested_baseline = max(means)
    safety = SAFETY_K[args.mode]
    suggested_baseline -= safety * stdev
    suggested_baseline = max(0.0, suggested_baseline)

    # 4. Trailing bias: derived from observed mean(BP) vs RT
    bp_vals = [float(r.get('bp_mm') or 0.0) for r in rows
                if r.get('zone','')=='MID']
    rt_vals = [float(r.get('rt_mm') or 0.0) for r in rows
                if r.get('zone','')=='MID']
    
    if bp_vals and rt_vals:
        observed_offset = stats.mean(bp_vals) - stats.mean(rt_vals)
        # If arm sits advance-of-target, raise bias to push it back.
        bias_delta = max(0.0, observed_offset / 7.8)   # threshold ≈ 7.8 mm
        bias_delta = min(0.4, bias_delta)              # cap suggested change
    else:
        bias_delta = 0.0

    # 5. Emit config.ini patch
    cp = configparser.ConfigParser()
    cp['nosf'] = {
        '_comment': '# generated by nosf_analyze.py',
        'baseline_rate_sps_suggestion': f'{suggested_baseline:.0f}',
        'sync_trailing_bias_frac_delta': f'{bias_delta:.3f}',
    }
    if args.feedforward:
        for (feat, v), s in sorted(summary.items()):
            cp['nosf'][f'ff_{feat}_v{v}'] = f"{s['mean']:.0f}"
    with open(args.out, 'w') as fh:
        fh.write('# nosf_analyze.py output\n')
        cp.write(fh)
    
    print(f"[*] Suggested baseline_rate_sps: {suggested_baseline:.0f}")
    print(f"[*] Suggested sync_trailing_bias_frac_delta: {bias_delta:.3f}")
    print(f"[*] Generated patch to {args.out}")

if __name__ == '__main__':
    main()
